### PR TITLE
allow for custom shouldBeRetried handler

### LINKED ISSUE #45: Allow custom 'should be retried' logic
Following the [discussion on #43](https://github.com/sindresorhus/p-retry/issues/43#issuecomment-809134850):

Currently, I can only opt out of retrying by throwing an `AbortError`. It's not possible to opt in to retrying for the cases that `p-retry` does not deem to be retry-worthy.

I'll draft a PR so we have a base for discussion.

### PR DESCRIPTION
**Pull request by stefanpl**
Closes #45 

I drafted this so we have something to discuss @sindresorhus. I'll add tests in case the general direction is agreed upon.

Of course, please feel free to edit or suggest changes as you see fit.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Should it be `shouldBeRetried` or `shouldRetry`?

**Comment by sindresorhus** [comment]
I think we also need to give the user the ability to set the `shouldBeRetried` option, but also easily get the default behavior if they want.

```js
shouldBeRetried: error => someCondition ? false : defaultBehavior,
```

Where `defaultBehavior` is the original `!(error instanceof TypeError) || error.isNetworkError` check. Not sure the best way to expose this. Could be `pRetry.defaultRetryLogic` or `error.isDefaultRetriable`. Or something better?

**Comment by acostalima** [comment]
I like `shouldRetry` better for the option. What if `pRetry` exposes a function with the same name, i.e., `shouldRetry`, to make it concise. The behaviour would be documented anyway.

**Comment by sindresorhus** [comment]
@stefanpl Friendly bump :)

**Pull request closed without merging**
