### PR TITLE
Fix on failed attempt

### LINKED ISSUE #11: onFailedAttempt returns wrong attempt counts
The error object returned in `onFailedAttempt` returns the wrong counts for the attempts.

```javascript
const retry = require('p-retry');

function test(times) {
  let c = 0;
  return function prom() {
    let p;

    if (times === c) {
      p = Promise.resolve('true');
    } else {
      p = Promise.reject(new Error('false'));
    }

    c += 1;

    return p;
  };
}

const f = test(3);

retry(f, {
  retries: 3,
  maxTimeout: 0,
  minTimeout: 0,
  onFailedAttempt(e) {
    console.log(`Attempt ${e.attemptNumber} failed. There are ${e.attemptsLeft} attempts left.`);
  },
})
  .then(v => {
    console.log('success', v);
  })
  .catch(e => {
    console.log('fail', e);
  });
```

The above prints out

```
$ node index.js
Attempt 1 failed. There are 2 attempts left.
Attempt 2 failed. There are 1 attempts left.
Attempt 3 failed. There are 0 attempts left.
success true
```

Maybe I'm using it wrong but if I have some type of logging in `onFailedAttempt` that checks to see if `error.attemptsLeft === 0` and then logs that an operation failed. That may not be true. The very last attempt could still succeed.

### PR DESCRIPTION
**Pull request by theverything**
This PR does a few things.

1. Corrects attempt counts.
2. Calls `onFailedAttempt` before final rejection.

---

Fixes #11

### CODE REVIEW

**Comment by theverything** [comment]
Fixes https://github.com/sindresorhus/p-retry/issues/11

**Comment by theverything** [comment]
ping @sindresorhus or @acostalima

**Comment by theverything** [comment]
@acostalima updated with your suggested changes

**Comment by acostalima** [comment]
@theverything everything looks fine to me 👍

**Comment by theverything** [comment]
@acostalima @sindresorhus any idea when this might get merged and published (should me a semver major)?

We're running a forked version until this lands and I'd like to get back to the official version.

**Comment by acostalima** [comment]
It has to be @sindresorhus to merge and publish. Yes, it will have to be a major release due to the breaking changed introduced.

**Comment by pragmaticivan** [comment]
@sindresorhus any way we could have @acostalima merging PRs on that repo? thanks!

**Comment by theverything** [comment]
pinging @sindresorhus

**Comment by theverything** [comment]
@sindresorhus will this ever be merged?

**Pull request merged**
