### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by zwtan**
Issue: currently it return resolve as attempts count but it should return it result instead

### CODE REVIEW

**Comment by SamVerschueren** [comment]
It returns the result. The thing you changed is that the input function now gets itself as first argument, which is clearly wrong. 

From the docs
> Receives the number of attempts as the first argument and is expected to return a Promise or any value.

And that is exactly what's happening.

**Comment by zwtan** [comment]
Thank for pointing that out, but currently is there anyway to retrieve it final result? I'm not able to get it resolve(data) It always return base on the number of attempts

**Comment by SamVerschueren** [comment]
It does resolve wherever the input function returns. https://github.com/sindresorhus/p-retry/blob/master/index.js#L28. That's what the code says and that's also what the tests say.

**Comment by zwtan** [comment]
Weirdly I'm getting number of attempt instead of my resolve(data) JSON

**Comment by SamVerschueren** [comment]
If you have a simple test case, feel free to paste it in here and I can have a look myself.

**Pull request closed without merging**
